import { Buttons } from "examples/buttons.slint";
import { MessageBox } from "examples/message-box.slint";
import { VerticalBox,ScrollView } from "std-widgets.slint";
import { Theme,Themes } from "themes/index.slint";


export component Examples inherits Window {
    width: 800px;
    height: 600px;

    VerticalBox {
        Text {
            text: "examples";
            font-weight: 800;
            font-size: 26px;
        }

        ScrollView {
            VerticalBox {
                Buttons {
                }

                Buttons {
                }

                MessageBox {
                }
            }
        }
    }
}
