import { Button,ButtonType,ButtonSize,ButtonRound } from "../widgets/button.slint";

import { HorizontalBox,VerticalBox } from "std-widgets.slint";

import { Themes,Theme } from "../themes/index.slint";

import { Title,SubTitle } from "title.slint";

export component Buttons {

    VerticalBox {

        Title{
            text: "Buttons";
        }

        SubTitle {
            text: "Default Buttons";
        }

        for size[index] in [ButtonSize.Default, ButtonSize.Medium, ButtonSize.Small, ButtonSize.Mini]: HorizontalBox {
            for type[index] in [
                ButtonType.Default,
                ButtonType.Primary,
                ButtonType.Success,
                ButtonType.Info,
                ButtonType.Warning,
                ButtonType.Danger
            ]: Button {
                size: size;
                type: type;
                text: "Button";
                clicked => {
                    debug(self.icon.width);
                }
            }
            Button {
                size: size;
                type: Default;
                round: Round;
                text: "Round Button";
            }

            Button {
                size: size;
                type: Default;
                icon: @image-url("home.svg");
                round: Circle;
            }
        }
        SubTitle {
            text: "Disabled Buttons";
            font-size: 18px;
        }

        HorizontalBox {
            for type[index] in [
                ButtonType.Default,
                ButtonType.Primary,
                ButtonType.Success,
                ButtonType.Info,
                ButtonType.Warning,
                ButtonType.Danger
            ]: Button {
                type: type;
                text: "Button";
                disabled: true;
            }
        }

        SubTitle {
            text: "Plain Buttons";
        }

        HorizontalBox {
            for type[index] in [
                ButtonType.Default,
                ButtonType.Primary,
                ButtonType.Success,
                ButtonType.Info,
                ButtonType.Warning,
                ButtonType.Danger
            ]: Button {
                type: type;
                text: "Button";
                plain: true;
            }
        }

        HorizontalBox {
            for type[index] in [
                ButtonType.Default,
                ButtonType.Primary,
                ButtonType.Success,
                ButtonType.Info,
                ButtonType.Warning,
                ButtonType.Danger
            ]: Button {
                type: type;
                plain: true;
                text: "Button";
                disabled: true;
            }
        }
    }
}
